name: Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  local-tests:
    runs-on: ubuntu-latest
    container:
      image: dolfinx/dolfinx:stable
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest pytest-mpi scipy pymanopt numpy matplotlib psutil
        pip install -e .
    - name: Verify PETSc complex support
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        python3 -c "import numpy as np; from petsc4py import PETSc; print('PETSc version:', PETSc.Sys.getVersion()); is_complex = PETSc.ScalarType == np.complex128; print('PETSc scalar type:', PETSc.ScalarType); print('Is complex?', is_complex); vec = PETSc.Vec().createWithArray(np.array([1+1j, 2+2j]), comm=PETSc.COMM_SELF); print('Successfully created complex vector!')"
    - name: Run local tests
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        mpirun -n 2 python3 -m pytest -v -m "local" tests/

  development-tests:
    runs-on: ubuntu-latest
    container:
      image: dolfinx/dolfinx:stable
    if: contains(github.ref, 'development')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest pytest-mpi scipy pymanopt numpy matplotlib psutil
        pip install -e .
    - name: Verify PETSc complex support
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        python3 -c "import numpy as np; from petsc4py import PETSc; print('PETSc version:', PETSc.Sys.getVersion()); is_complex = PETSc.ScalarType == np.complex128; print('PETSc scalar type:', PETSc.ScalarType); print('Is complex?', is_complex); vec = PETSc.Vec().createWithArray(np.array([1+1j, 2+2j]), comm=PETSc.COMM_SELF); print('Successfully created complex vector!')"
    - name: Run development tests
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        mpirun -n 2 python3 -m pytest -v -m "development" tests/

  main-tests:
    runs-on: ubuntu-latest
    container:
      image: dolfinx/dolfinx:stable
    if: contains(github.ref, 'main')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest pytest-mpi scipy pymanopt numpy matplotlib psutil
        pip install -e .
    - name: Verify PETSc complex support
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        python3 -c "import numpy as np; from petsc4py import PETSc; print('PETSc version:', PETSc.Sys.getVersion()); is_complex = PETSc.ScalarType == np.complex128; print('PETSc scalar type:', PETSc.ScalarType); print('Is complex?', is_complex); vec = PETSc.Vec().createWithArray(np.array([1+1j, 2+2j]), comm=PETSc.COMM_SELF); print('Successfully created complex vector!')"
    - name: Run main tests
      run: |
        export PETSC_ARCH=linux-gnu-complex128-32
        export PETSC4PY_COMPLEX=1
        mpirun -n 2 python3 -m pytest -v -m "main" tests/